// <auto-generated />
using BEER_WEB_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BEER_WEB_API.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220221124958_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BEER_WEB_API.Models.Entities.BeerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AlcoholContent")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BeerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BestBeforeDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("BottleSize")
                        .HasColumnType("decimal(3,0)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.Property<string>("Purchased")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(3,0)");

                    b.Property<decimal>("Vintage")
                        .HasColumnType("decimal(4,0)");

                    b.HasKey("Id");

                    b.HasIndex("ProductsId");

                    b.ToTable("Beers");
                });

            modelBuilder.Entity("BEER_WEB_API.Models.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BeerStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brewery")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BEER_WEB_API.Models.Entities.BeerEntity", b =>
                {
                    b.HasOne("BEER_WEB_API.Models.Entities.ProductEntity", "Products")
                        .WithMany("Beers")
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("BEER_WEB_API.Models.Entities.ProductEntity", b =>
                {
                    b.Navigation("Beers");
                });
#pragma warning restore 612, 618
        }
    }
}
